/*
 * REST API
 *
 * This document describes the official AlphaSOC REST API. The primary purpose of the API is to allow a wide variety of clients for sending network telemetry and receiving alerts. API endpoints are complementary to other [data sources](/sources/data-ingestion/) and [alert escalations](/destinations/alert-escalation/) in a way that alerts generated for network telemetry submitted outside of the API are available to download via API and vice versa.  ## Schema  The API can be accessed at `https://api.alphasoc.net` over HTTPS. All requests and responses are encoded in JSON.  ## Compression  As the amount of data transmitted via API can be high, it's advisable to use the compression both ways. Usually HTTP clients transparently support compression when fetching data (by providing `Accept-Encoding` header), but the upload needs to be handled manually. AlphaSOC API supports `gzip` and `deflate` compression algorithms and it's recommended to compress large chunks of data (telemetry) before sending, along with attaching corresponding `Content-Encoding` header.  ## Rate limiting  API counts and limits number of requests from a single API key. The limits are not strictly defined and designed to protect from flooding and accidental errors in client's implementation. In the unlikely case of hitting the limit API returns `429 Too Many Requests` response and expects the client to retry after some time.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alphasoc

import (
	"encoding/json"
)

// Wisdom struct for Wisdom
type Wisdom struct {
	Flags  *[]string `json:"flags,omitempty"`
	Labels *[]string `json:"labels,omitempty"`
	Domain *string   `json:"domain,omitempty"`
}

// NewWisdom instantiates a new Wisdom object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWisdom() *Wisdom {
	this := Wisdom{}
	return &this
}

// NewWisdomWithDefaults instantiates a new Wisdom object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWisdomWithDefaults() *Wisdom {
	this := Wisdom{}
	return &this
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *Wisdom) GetFlags() []string {
	if o == nil || o.Flags == nil {
		var ret []string
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wisdom) GetFlagsOk() (*[]string, bool) {
	if o == nil || o.Flags == nil {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *Wisdom) HasFlags() bool {
	if o != nil && o.Flags != nil {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *Wisdom) SetFlags(v []string) {
	o.Flags = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Wisdom) GetLabels() []string {
	if o == nil || o.Labels == nil {
		var ret []string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wisdom) GetLabelsOk() (*[]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Wisdom) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *Wisdom) SetLabels(v []string) {
	o.Labels = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *Wisdom) GetDomain() string {
	if o == nil || o.Domain == nil {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wisdom) GetDomainOk() (*string, bool) {
	if o == nil || o.Domain == nil {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *Wisdom) HasDomain() bool {
	if o != nil && o.Domain != nil {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *Wisdom) SetDomain(v string) {
	o.Domain = &v
}

func (o Wisdom) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Flags != nil {
		toSerialize["flags"] = o.Flags
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Domain != nil {
		toSerialize["domain"] = o.Domain
	}
	return json.Marshal(toSerialize)
}

type NullableWisdom struct {
	value *Wisdom
	isSet bool
}

func (v NullableWisdom) Get() *Wisdom {
	return v.value
}

func (v *NullableWisdom) Set(val *Wisdom) {
	v.value = val
	v.isSet = true
}

func (v NullableWisdom) IsSet() bool {
	return v.isSet
}

func (v *NullableWisdom) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWisdom(val *Wisdom) *NullableWisdom {
	return &NullableWisdom{value: val, isSet: true}
}

func (v NullableWisdom) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWisdom) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
