/*
 * AlphaSOC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// TlsEventAllOf struct for TlsEventAllOf
type TlsEventAllOf struct {
	CertHash *string `json:"certHash,omitempty"`
	Issuer *string `json:"issuer,omitempty"`
	Subject *string `json:"subject,omitempty"`
	ValidFrom *time.Time `json:"validFrom,omitempty"`
	ValidTo *time.Time `json:"validTo,omitempty"`
	DestIP *string `json:"destIP,omitempty"`
	DestPort *int32 `json:"destPort,omitempty"`
	Ja3 *string `json:"ja3,omitempty"`
	Ja3s *string `json:"ja3s,omitempty"`
}

// NewTlsEventAllOf instantiates a new TlsEventAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTlsEventAllOf() *TlsEventAllOf {
	this := TlsEventAllOf{}
	return &this
}

// NewTlsEventAllOfWithDefaults instantiates a new TlsEventAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTlsEventAllOfWithDefaults() *TlsEventAllOf {
	this := TlsEventAllOf{}
	return &this
}

// GetCertHash returns the CertHash field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetCertHash() string {
	if o == nil || o.CertHash == nil {
		var ret string
		return ret
	}
	return *o.CertHash
}

// GetCertHashOk returns a tuple with the CertHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetCertHashOk() (*string, bool) {
	if o == nil || o.CertHash == nil {
		return nil, false
	}
	return o.CertHash, true
}

// HasCertHash returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasCertHash() bool {
	if o != nil && o.CertHash != nil {
		return true
	}

	return false
}

// SetCertHash gets a reference to the given string and assigns it to the CertHash field.
func (o *TlsEventAllOf) SetCertHash(v string) {
	o.CertHash = &v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetIssuer() string {
	if o == nil || o.Issuer == nil {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetIssuerOk() (*string, bool) {
	if o == nil || o.Issuer == nil {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasIssuer() bool {
	if o != nil && o.Issuer != nil {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *TlsEventAllOf) SetIssuer(v string) {
	o.Issuer = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetSubject() string {
	if o == nil || o.Subject == nil {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetSubjectOk() (*string, bool) {
	if o == nil || o.Subject == nil {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasSubject() bool {
	if o != nil && o.Subject != nil {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *TlsEventAllOf) SetSubject(v string) {
	o.Subject = &v
}

// GetValidFrom returns the ValidFrom field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetValidFrom() time.Time {
	if o == nil || o.ValidFrom == nil {
		var ret time.Time
		return ret
	}
	return *o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetValidFromOk() (*time.Time, bool) {
	if o == nil || o.ValidFrom == nil {
		return nil, false
	}
	return o.ValidFrom, true
}

// HasValidFrom returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasValidFrom() bool {
	if o != nil && o.ValidFrom != nil {
		return true
	}

	return false
}

// SetValidFrom gets a reference to the given time.Time and assigns it to the ValidFrom field.
func (o *TlsEventAllOf) SetValidFrom(v time.Time) {
	o.ValidFrom = &v
}

// GetValidTo returns the ValidTo field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetValidTo() time.Time {
	if o == nil || o.ValidTo == nil {
		var ret time.Time
		return ret
	}
	return *o.ValidTo
}

// GetValidToOk returns a tuple with the ValidTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetValidToOk() (*time.Time, bool) {
	if o == nil || o.ValidTo == nil {
		return nil, false
	}
	return o.ValidTo, true
}

// HasValidTo returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasValidTo() bool {
	if o != nil && o.ValidTo != nil {
		return true
	}

	return false
}

// SetValidTo gets a reference to the given time.Time and assigns it to the ValidTo field.
func (o *TlsEventAllOf) SetValidTo(v time.Time) {
	o.ValidTo = &v
}

// GetDestIP returns the DestIP field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetDestIP() string {
	if o == nil || o.DestIP == nil {
		var ret string
		return ret
	}
	return *o.DestIP
}

// GetDestIPOk returns a tuple with the DestIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetDestIPOk() (*string, bool) {
	if o == nil || o.DestIP == nil {
		return nil, false
	}
	return o.DestIP, true
}

// HasDestIP returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasDestIP() bool {
	if o != nil && o.DestIP != nil {
		return true
	}

	return false
}

// SetDestIP gets a reference to the given string and assigns it to the DestIP field.
func (o *TlsEventAllOf) SetDestIP(v string) {
	o.DestIP = &v
}

// GetDestPort returns the DestPort field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetDestPort() int32 {
	if o == nil || o.DestPort == nil {
		var ret int32
		return ret
	}
	return *o.DestPort
}

// GetDestPortOk returns a tuple with the DestPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetDestPortOk() (*int32, bool) {
	if o == nil || o.DestPort == nil {
		return nil, false
	}
	return o.DestPort, true
}

// HasDestPort returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasDestPort() bool {
	if o != nil && o.DestPort != nil {
		return true
	}

	return false
}

// SetDestPort gets a reference to the given int32 and assigns it to the DestPort field.
func (o *TlsEventAllOf) SetDestPort(v int32) {
	o.DestPort = &v
}

// GetJa3 returns the Ja3 field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetJa3() string {
	if o == nil || o.Ja3 == nil {
		var ret string
		return ret
	}
	return *o.Ja3
}

// GetJa3Ok returns a tuple with the Ja3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetJa3Ok() (*string, bool) {
	if o == nil || o.Ja3 == nil {
		return nil, false
	}
	return o.Ja3, true
}

// HasJa3 returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasJa3() bool {
	if o != nil && o.Ja3 != nil {
		return true
	}

	return false
}

// SetJa3 gets a reference to the given string and assigns it to the Ja3 field.
func (o *TlsEventAllOf) SetJa3(v string) {
	o.Ja3 = &v
}

// GetJa3s returns the Ja3s field value if set, zero value otherwise.
func (o *TlsEventAllOf) GetJa3s() string {
	if o == nil || o.Ja3s == nil {
		var ret string
		return ret
	}
	return *o.Ja3s
}

// GetJa3sOk returns a tuple with the Ja3s field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsEventAllOf) GetJa3sOk() (*string, bool) {
	if o == nil || o.Ja3s == nil {
		return nil, false
	}
	return o.Ja3s, true
}

// HasJa3s returns a boolean if a field has been set.
func (o *TlsEventAllOf) HasJa3s() bool {
	if o != nil && o.Ja3s != nil {
		return true
	}

	return false
}

// SetJa3s gets a reference to the given string and assigns it to the Ja3s field.
func (o *TlsEventAllOf) SetJa3s(v string) {
	o.Ja3s = &v
}

func (o TlsEventAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CertHash != nil {
		toSerialize["certHash"] = o.CertHash
	}
	if o.Issuer != nil {
		toSerialize["issuer"] = o.Issuer
	}
	if o.Subject != nil {
		toSerialize["subject"] = o.Subject
	}
	if o.ValidFrom != nil {
		toSerialize["validFrom"] = o.ValidFrom
	}
	if o.ValidTo != nil {
		toSerialize["validTo"] = o.ValidTo
	}
	if o.DestIP != nil {
		toSerialize["destIP"] = o.DestIP
	}
	if o.DestPort != nil {
		toSerialize["destPort"] = o.DestPort
	}
	if o.Ja3 != nil {
		toSerialize["ja3"] = o.Ja3
	}
	if o.Ja3s != nil {
		toSerialize["ja3s"] = o.Ja3s
	}
	return json.Marshal(toSerialize)
}

type NullableTlsEventAllOf struct {
	value *TlsEventAllOf
	isSet bool
}

func (v NullableTlsEventAllOf) Get() *TlsEventAllOf {
	return v.value
}

func (v *NullableTlsEventAllOf) Set(val *TlsEventAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTlsEventAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTlsEventAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTlsEventAllOf(val *TlsEventAllOf) *NullableTlsEventAllOf {
	return &NullableTlsEventAllOf{value: val, isSet: true}
}

func (v NullableTlsEventAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTlsEventAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


