/*
 * REST API
 *
 * This document describes the official AlphaSOC REST API. The primary purpose of the API is to allow a wide variety of clients for sending network telemetry and receiving alerts. API endpoints are complementary to other [data sources](/sources/data-ingestion/) and [alert escalations](/destinations/alert-escalation/) in a way that alerts generated for network telemetry submitted outside of the API are available to download via API and vice versa.  ## Schema  The API can be accessed at `https://api.alphasoc.net` over HTTPS. All requests and responses are encoded in JSON.  ## Compression  As the amount of data transmitted via API can be high, it's advisable to use the compression both ways. Usually HTTP clients transparently support compression when fetching data (by providing `Accept-Encoding` header), but the upload needs to be handled manually. AlphaSOC API supports `gzip` and `deflate` compression algorithms and it's recommended to compress large chunks of data (telemetry) before sending, along with attaching corresponding `Content-Encoding` header.  ## Rate limiting  API counts and limits number of requests from a single API key. The limits are not strictly defined and designed to protect from flooding and accidental errors in client's implementation. In the unlikely case of hitting the limit API returns `429 Too Many Requests` response and expects the client to retry after some time.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alphasoc

import (
	"encoding/json"
)

// Alert struct for Alert
type Alert struct {
	// EventType describes type of event object (\"dns\", \"ip\", \"http\", \"tls\").
	EventType *string `json:"eventType,omitempty"`
	// Threats associated with alert.
	Threats *[]string `json:"threats,omitempty"`
	Wisdom  *Wisdom   `json:"wisdom,omitempty"`
	// One of the *Event schema described in the table below.
	Event json.RawMessage `json:"event,omitempty"`
}

// NewAlert instantiates a new Alert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlert() *Alert {
	this := Alert{}
	return &this
}

// NewAlertWithDefaults instantiates a new Alert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertWithDefaults() *Alert {
	this := Alert{}
	return &this
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *Alert) GetEventType() string {
	if o == nil || o.EventType == nil {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetEventTypeOk() (*string, bool) {
	if o == nil || o.EventType == nil {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *Alert) HasEventType() bool {
	if o != nil && o.EventType != nil {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *Alert) SetEventType(v string) {
	o.EventType = &v
}

// GetThreats returns the Threats field value if set, zero value otherwise.
func (o *Alert) GetThreats() []string {
	if o == nil || o.Threats == nil {
		var ret []string
		return ret
	}
	return *o.Threats
}

// GetThreatsOk returns a tuple with the Threats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetThreatsOk() (*[]string, bool) {
	if o == nil || o.Threats == nil {
		return nil, false
	}
	return o.Threats, true
}

// HasThreats returns a boolean if a field has been set.
func (o *Alert) HasThreats() bool {
	if o != nil && o.Threats != nil {
		return true
	}

	return false
}

// SetThreats gets a reference to the given []string and assigns it to the Threats field.
func (o *Alert) SetThreats(v []string) {
	o.Threats = &v
}

// GetWisdom returns the Wisdom field value if set, zero value otherwise.
func (o *Alert) GetWisdom() Wisdom {
	if o == nil || o.Wisdom == nil {
		var ret Wisdom
		return ret
	}
	return *o.Wisdom
}

// GetWisdomOk returns a tuple with the Wisdom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetWisdomOk() (*Wisdom, bool) {
	if o == nil || o.Wisdom == nil {
		return nil, false
	}
	return o.Wisdom, true
}

// HasWisdom returns a boolean if a field has been set.
func (o *Alert) HasWisdom() bool {
	if o != nil && o.Wisdom != nil {
		return true
	}

	return false
}

// SetWisdom gets a reference to the given Wisdom and assigns it to the Wisdom field.
func (o *Alert) SetWisdom(v Wisdom) {
	o.Wisdom = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *Alert) GetEvent() json.RawMessage {
	if o == nil || o.Event == nil {
		var ret json.RawMessage
		return ret
	}
	return o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetEventOk() (json.RawMessage, bool) {
	if o == nil || o.Event == nil {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *Alert) HasEvent() bool {
	if o != nil && o.Event != nil {
		return true
	}

	return false
}

// SetEvent gets a reference to the given json.RawMessage and assigns it to the Event field.
func (o *Alert) SetEvent(v json.RawMessage) {
	o.Event = v
}

func (o Alert) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EventType != nil {
		toSerialize["eventType"] = o.EventType
	}
	if o.Threats != nil {
		toSerialize["threats"] = o.Threats
	}
	if o.Wisdom != nil {
		toSerialize["wisdom"] = o.Wisdom
	}
	if o.Event != nil {
		toSerialize["event"] = o.Event
	}
	return json.Marshal(toSerialize)
}

type NullableAlert struct {
	value *Alert
	isSet bool
}

func (v NullableAlert) Get() *Alert {
	return v.value
}

func (v *NullableAlert) Set(val *Alert) {
	v.value = val
	v.isSet = true
}

func (v NullableAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlert(val *Alert) *NullableAlert {
	return &NullableAlert{value: val, isSet: true}
}

func (v NullableAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
