/*
 * REST API
 *
 * This document describes the official AlphaSOC REST API. The primary purpose of the API is to allow a wide variety of clients for sending network telemetry and receiving alerts. API endpoints are complementary to other [data sources](/sources/data-ingestion/) and [alert escalations](/destinations/alert-escalation/) in a way that alerts generated for network telemetry submitted outside of the API are available to download via API and vice versa.  ## Schema  The API can be accessed at `https://api.alphasoc.net` over HTTPS. All requests and responses are encoded in JSON.  ## Compression  As the amount of data transmitted via API can be high, it's advisable to use the compression both ways. Usually HTTP clients transparently support compression when fetching data (by providing `Accept-Encoding` header), but the upload needs to be handled manually. AlphaSOC API supports `gzip` and `deflate` compression algorithms and it's recommended to compress large chunks of data (telemetry) before sending, along with attaching corresponding `Content-Encoding` header.  ## Rate limiting  API counts and limits number of requests from a single API key. The limits are not strictly defined and designed to protect from flooding and accidental errors in client's implementation. In the unlikely case of hitting the limit API returns `429 Too Many Requests` response and expects the client to retry after some time.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alphasoc

import (
	"encoding/json"
)

// KeyRequestResponseBody struct for KeyRequestResponseBody
type KeyRequestResponseBody struct {
	Key *string `json:"key,omitempty"`
}

// NewKeyRequestResponseBody instantiates a new KeyRequestResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyRequestResponseBody() *KeyRequestResponseBody {
	this := KeyRequestResponseBody{}
	return &this
}

// NewKeyRequestResponseBodyWithDefaults instantiates a new KeyRequestResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyRequestResponseBodyWithDefaults() *KeyRequestResponseBody {
	this := KeyRequestResponseBody{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *KeyRequestResponseBody) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyRequestResponseBody) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *KeyRequestResponseBody) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *KeyRequestResponseBody) SetKey(v string) {
	o.Key = &v
}

func (o KeyRequestResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullableKeyRequestResponseBody struct {
	value *KeyRequestResponseBody
	isSet bool
}

func (v NullableKeyRequestResponseBody) Get() *KeyRequestResponseBody {
	return v.value
}

func (v *NullableKeyRequestResponseBody) Set(val *KeyRequestResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyRequestResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyRequestResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyRequestResponseBody(val *KeyRequestResponseBody) *NullableKeyRequestResponseBody {
	return &NullableKeyRequestResponseBody{value: val, isSet: true}
}

func (v NullableKeyRequestResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyRequestResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
