/*
 * AlphaSOC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KeyRequestBodyAllOf struct for KeyRequestBodyAllOf
type KeyRequestBodyAllOf struct {
	Uname *string `json:"uname,omitempty"`
	Token *string `json:"token,omitempty"`
}

// NewKeyRequestBodyAllOf instantiates a new KeyRequestBodyAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyRequestBodyAllOf() *KeyRequestBodyAllOf {
	this := KeyRequestBodyAllOf{}
	return &this
}

// NewKeyRequestBodyAllOfWithDefaults instantiates a new KeyRequestBodyAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyRequestBodyAllOfWithDefaults() *KeyRequestBodyAllOf {
	this := KeyRequestBodyAllOf{}
	return &this
}

// GetUname returns the Uname field value if set, zero value otherwise.
func (o *KeyRequestBodyAllOf) GetUname() string {
	if o == nil || o.Uname == nil {
		var ret string
		return ret
	}
	return *o.Uname
}

// GetUnameOk returns a tuple with the Uname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyRequestBodyAllOf) GetUnameOk() (*string, bool) {
	if o == nil || o.Uname == nil {
		return nil, false
	}
	return o.Uname, true
}

// HasUname returns a boolean if a field has been set.
func (o *KeyRequestBodyAllOf) HasUname() bool {
	if o != nil && o.Uname != nil {
		return true
	}

	return false
}

// SetUname gets a reference to the given string and assigns it to the Uname field.
func (o *KeyRequestBodyAllOf) SetUname(v string) {
	o.Uname = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *KeyRequestBodyAllOf) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyRequestBodyAllOf) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *KeyRequestBodyAllOf) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *KeyRequestBodyAllOf) SetToken(v string) {
	o.Token = &v
}

func (o KeyRequestBodyAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uname != nil {
		toSerialize["uname"] = o.Uname
	}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableKeyRequestBodyAllOf struct {
	value *KeyRequestBodyAllOf
	isSet bool
}

func (v NullableKeyRequestBodyAllOf) Get() *KeyRequestBodyAllOf {
	return v.value
}

func (v *NullableKeyRequestBodyAllOf) Set(val *KeyRequestBodyAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyRequestBodyAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyRequestBodyAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyRequestBodyAllOf(val *KeyRequestBodyAllOf) *NullableKeyRequestBodyAllOf {
	return &NullableKeyRequestBodyAllOf{value: val, isSet: true}
}

func (v NullableKeyRequestBodyAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyRequestBodyAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


