/*
 * REST API
 *
 * This document describes the official AlphaSOC REST API. The primary purpose of the API is to allow a wide variety of clients for sending network telemetry and receiving alerts. API endpoints are complementary to other [data sources](/sources/data-ingestion/) and [alert escalations](/destinations/alert-escalation/) in a way that alerts generated for network telemetry submitted outside of the API are available to download via API and vice versa.  ## Schema  The API can be accessed at `https://api.alphasoc.net` over HTTPS. All requests and responses are encoded in JSON.  ## Compression  As the amount of data transmitted via API can be high, it's advisable to use the compression both ways. Usually HTTP clients transparently support compression when fetching data (by providing `Accept-Encoding` header), but the upload needs to be handled manually. AlphaSOC API supports `gzip` and `deflate` compression algorithms and it's recommended to compress large chunks of data (telemetry) before sending, along with attaching corresponding `Content-Encoding` header.  ## Rate limiting  API counts and limits number of requests from a single API key. The limits are not strictly defined and designed to protect from flooding and accidental errors in client's implementation. In the unlikely case of hitting the limit API returns `429 Too Many Requests` response and expects the client to retry after some time.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// EventsResponseBody struct for EventsResponseBody
type EventsResponseBody struct {
	// Number of received events
	Received *int32 `json:"received,omitempty"`
	// Number of accepted events
	Accepted *int32 `json:"accepted,omitempty"`
}

// NewEventsResponseBody instantiates a new EventsResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsResponseBody() *EventsResponseBody {
	this := EventsResponseBody{}
	return &this
}

// NewEventsResponseBodyWithDefaults instantiates a new EventsResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsResponseBodyWithDefaults() *EventsResponseBody {
	this := EventsResponseBody{}
	return &this
}

// GetReceived returns the Received field value if set, zero value otherwise.
func (o *EventsResponseBody) GetReceived() int32 {
	if o == nil || o.Received == nil {
		var ret int32
		return ret
	}
	return *o.Received
}

// GetReceivedOk returns a tuple with the Received field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsResponseBody) GetReceivedOk() (*int32, bool) {
	if o == nil || o.Received == nil {
		return nil, false
	}
	return o.Received, true
}

// HasReceived returns a boolean if a field has been set.
func (o *EventsResponseBody) HasReceived() bool {
	if o != nil && o.Received != nil {
		return true
	}

	return false
}

// SetReceived gets a reference to the given int32 and assigns it to the Received field.
func (o *EventsResponseBody) SetReceived(v int32) {
	o.Received = &v
}

// GetAccepted returns the Accepted field value if set, zero value otherwise.
func (o *EventsResponseBody) GetAccepted() int32 {
	if o == nil || o.Accepted == nil {
		var ret int32
		return ret
	}
	return *o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsResponseBody) GetAcceptedOk() (*int32, bool) {
	if o == nil || o.Accepted == nil {
		return nil, false
	}
	return o.Accepted, true
}

// HasAccepted returns a boolean if a field has been set.
func (o *EventsResponseBody) HasAccepted() bool {
	if o != nil && o.Accepted != nil {
		return true
	}

	return false
}

// SetAccepted gets a reference to the given int32 and assigns it to the Accepted field.
func (o *EventsResponseBody) SetAccepted(v int32) {
	o.Accepted = &v
}

func (o EventsResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Received != nil {
		toSerialize["received"] = o.Received
	}
	if o.Accepted != nil {
		toSerialize["accepted"] = o.Accepted
	}
	return json.Marshal(toSerialize)
}

type NullableEventsResponseBody struct {
	value *EventsResponseBody
	isSet bool
}

func (v NullableEventsResponseBody) Get() *EventsResponseBody {
	return v.value
}

func (v *NullableEventsResponseBody) Set(val *EventsResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsResponseBody(val *EventsResponseBody) *NullableEventsResponseBody {
	return &NullableEventsResponseBody{value: val, isSet: true}
}

func (v NullableEventsResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
